TYPES = ["location", "rotation_euler", "scale"]
TYPES_ENUM_ITEMS = [("LOCATION", "Location", "Location"), ("ROTATION_EULER", "Rotation Euler", "Rotation Euler"), ("SCALE", "Scale", "Scale")]
AXIS = ["X", "Y", "Z"]
AXIS_ENUM_ITEMS = [("X", "X Axis", "X Axis"), ("Y", "Y Axis", "Y Axis"), ("Z", "Z Axis", "Z Axis")]
FPS_MODES = [24, 30, 60]
FPS_MODES_ENUM = [("24", "24 fps", "24 Frames per Second"), ("30", "30 fps", "30 Frames per Second"), ("60", "60 fps", "60 Frames per Second")]